### PR TITLE
Fix graphql Error

### PR DESCRIPTION
**Pull request by ShadyNagy**
**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by ardalis** [comment]
Did you update this based on what you discovered about the source of the error?

**Comment by ShadyNagy** [comment]
> 
> 
> Did you update this based on what you discovered about the source of the error?

It is packages comaptibility problem so this working together.

**Comment by ShadyNagy** [comment]
gatsby-remark-relative-images & gatsby-remark-images downgraded.

**Comment by ardalis** [comment]
"gatsby-remark-relative-images version 0.3.0 has problem but version 0.2.1 working good"

**Comment by ardalis** [comment]
(I was hoping for another commit with the right numbers, but I'll sort it out)

**Pull request merged**
