### PR TITLE
build sitemap

### PR DESCRIPTION
**Pull request by emmadigital**
**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

I created another branch to generate sitemap, please review and accept PR.

### CODE REVIEW

**Comment by emmadigital** [comment]
Updated the npm packages and config file. Kindly review and accept changes.

**Comment by ardalis** [comment]
Looks like this PR worked!

**Comment by ardalis** [comment]
You should be able to use this same technique to make a pull request to add social media card support. Thanks!

**Comment by emmadigital** [comment]
Great! I will update the social cards as well today and will send you the new PR request.

**Pull request merged**
